--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.358.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 09/06/2017 15:08:36
-- Server version: 5.5.55-0ubuntu0.14.04.1
-- Client version: 4.1
--


DROP TABLE IF EXISTS v_ccm;

CREATE OR REPLACE
DEFINER = 'root'@'%'
VIEW v_ccm
AS
SELECT
  `dtl`.`dtlvalor` AS `dtlvalor`,
  `cco`.`ctacodigo` AS `ctacodigo`,
  `cco`.`clbcodigo` AS `clbcodigo`,
  `cco`.`ccoemissao` AS `ccoemissao`,
  `cco`.`ccovencimento` AS `ccovencimento`,
  `cco`.`ccohistorico` AS `ccohistorico`,
  `cco`.`cconumero` AS `cconumero`,
  `cco`.`ccofavorecido` AS `ccofavorecido`,
  `cco`.`ccodataregistro` AS `ccodataregistro`,
  `cco`.`ccohoraregistro` AS `ccohoraregistro`,
  `cco`.`phgcodigo` AS `phgcodigo`,
  `mda`.`mdaidentificacao` AS `mdaidentificacao`,
  `cco`.`ccoconciliado` AS `ccoconciliado`,
  `phg`.`phgidentificacao` AS `phgidentificacao`,
  `cco`.`ccochave` AS `ccochave`,
  `dtl`.`cedcodigo` AS `cedcodigo`,
  `cco`.`tficodigo` AS `tficodigo`,
  `cco`.`toccodigo` AS `toccodigo`,
  `tfi`.`tfiidentificacao` AS `tfiidentificacao`,
  `toc`.`tocidentificacao` AS `tocidentificacao`
FROM ((((((`clt`
  JOIN `cco`
    ON ((`clt`.`ccochave` = `cco`.`ccochave`)))
  JOIN `dtl`
    ON ((`clt`.`ltechave` = `dtl`.`ltechave`)))
  JOIN `mda`
    ON ((`dtl`.`mdacodigo` = `mda`.`mdacodigo`)))
  LEFT JOIN `phg`
    ON ((`cco`.`phgcodigo` = `phg`.`phgcodigo`)))
  JOIN `tfi`
    ON ((`cco`.`tficodigo` = `tfi`.`tficodigo`)))
  JOIN `toc`
    ON ((`cco`.`toccodigo` = `toc`.`toccodigo`)));

DROP TABLE IF EXISTS v_chd;

CREATE OR REPLACE
DEFINER = 'root'@'%'
VIEW v_chd
AS
SELECT
  `chd`.`chdchave` AS `chdchave`,
  `tcm`.`tcmidentificacao` AS `tcmidentificacao`,
  `chd`.`chdidentificacao` AS `chdidentificacao`,
  `chd`.`ttccodigo` AS `ttccodigo`,
  `chd`.`tcmcodigo` AS `tcmcodigo`,
  `chd`.`tprcodigo` AS `tprcodigo`,
  `chd`.`chdregistro` AS `chdregistro`,
  CAST((SELECT
      `e`.`echregistro`
    FROM `ech` `e`
    WHERE (`e`.`chdchave` = `chd`.`chdchave`)
    ORDER BY `e`.`echchave` DESC LIMIT 1) AS date) AS `chddata`,
  `chd`.`etdcodigo` AS `etdcodigo`,
  `chd`.`tsoemail` AS `tsoemail`,
  `chd`.`chddescricao` AS `chddescricao`,
  `etd`.`etdidentificacao` AS `etdidentificacao`,
  `etd`.`etdapelido` AS `etdapelido`,
  `chd`.`chddataatendimento` AS `chddataatendimento`,
  `ttc`.`ttcidentificacao` AS `ttcidentificacao`,
  `tpr`.`tpridentificacao` AS `tpridentificacao`,
  `tso`.`tsoidentificacao` AS `tsoidentificacao`,
  (SELECT
      `tec`.`tecidentificacao`
    FROM (`tec`
      JOIN `ech` `e`)
    WHERE ((`tec`.`teccodigo` = `e`.`teccodigo`)
    AND (`e`.`chdchave` = `chd`.`chdchave`))
    ORDER BY `e`.`echchave` DESC LIMIT 1) AS `tecidentificacao`,
  `etf`.`etftelefone` AS `etftelefone`,
  `clb`.`clbidentificacao` AS `clbidentificacao`,
  `tpr`.`tprcor` AS `tprcor`,
  (SELECT
      `tec`.`teccor`
    FROM (`tec`
      JOIN `ech` `e`)
    WHERE ((`tec`.`teccodigo` = `e`.`teccodigo`)
    AND (`e`.`chdchave` = `chd`.`chdchave`))
    ORDER BY `e`.`echchave` DESC LIMIT 1) AS `teccor`,
  (SELECT
      `tec`.`tecsituacao`
    FROM (`tec`
      JOIN `ech` `e`)
    WHERE ((`tec`.`teccodigo` = `e`.`teccodigo`)
    AND (`e`.`chdchave` = `chd`.`chdchave`))
    ORDER BY `e`.`echchave` DESC LIMIT 1) AS `tecsituacao`,
  (SELECT
      `tec`.`teccodigo`
    FROM (`tec`
      JOIN `ech` `e`)
    WHERE ((`tec`.`teccodigo` = `e`.`teccodigo`)
    AND (`e`.`chdchave` = `chd`.`chdchave`))
    ORDER BY `e`.`echchave` DESC LIMIT 1) AS `teccodigo`
FROM ((((((((`chd`
  JOIN `tso`
    ON ((`chd`.`tsoemail` = `tso`.`tsoemail`)))
  JOIN `tpr`
    ON ((`chd`.`tprcodigo` = `tpr`.`tprcodigo`)))
  JOIN `tcm`
    ON ((`chd`.`tcmcodigo` = `tcm`.`tcmcodigo`)))
  JOIN `ttc`
    ON ((`chd`.`ttccodigo` = `ttc`.`ttccodigo`)))
  JOIN `etd`
    ON ((`chd`.`etdcodigo` = `etd`.`etdcodigo`)))
  JOIN `etf`
    ON (((`chd`.`etdcodigo` = `etf`.`etdcodigo`)
    AND (`etf`.`ttfcodigo` = 1))))
  LEFT JOIN `rch`
    ON (((`chd`.`chdchave` = `rch`.`chdchave`)
    AND (`rch`.`rchchave` = (SELECT
        MAX(`rch`.`rchchave`) AS `rchchave`
      FROM `rch`
      WHERE (`rch`.`chdchave` = `chd`.`chdchave`) LIMIT 1)))))
  LEFT JOIN `clb`
    ON ((`rch`.`clbcodigo` = `clb`.`clbcodigo`)));

DROP TABLE IF EXISTS v_enp;

CREATE OR REPLACE
DEFINER = 'root'@'localhost'
VIEW v_enp
AS
SELECT
  `enp`.`enpcodigo` AS `enpcodigo`,
  CAST(CONCAT(`are`.`areidentificacao`, '.', `rue`.`rueidentificacao`, '.', `pde`.`pdeidentificacao`, '.', `ane`.`aneidentificacao`) AS char charset latin1) AS `enpendereco`
FROM ((((`enp`
  JOIN `are`)
  JOIN `rue`)
  JOIN `pde`)
  JOIN `ane`)
WHERE ((`are`.`arecodigo` = `enp`.`arecodigo`)
AND (`rue`.`ruecodigo` = `enp`.`ruecodigo`)
AND (`pde`.`pdecodigo` = `enp`.`pdecodigo`)
AND (`ane`.`anecodigo` = `enp`.`anecodigo`));


DROP TABLE IF EXISTS v_mce;

CREATE OR REPLACE
DEFINER = 'root'@'%'
VIEW v_mce
AS
SELECT
  MAX(`mce`.`mcechave`) AS `mcechave`,
  `mce`.`rcrchave` AS `rcrchave`
FROM `mce`
GROUP BY `mce`.`rcrchave`;

DROP TABLE IF EXISTS v_mcr;

CREATE OR REPLACE
DEFINER = 'root'@'%'
VIEW v_mcr
AS
SELECT
  SUM(`mcr`.`mcrvalor`) AS `mcrvalor`,
  `mcr`.`rcrchave` AS `rcrchave`
FROM `mcr`
GROUP BY `mcr`.`rcrchave`;

DROP TABLE IF EXISTS v_orc_etd;

CREATE OR REPLACE
DEFINER = 'root'@'localhost'
VIEW v_orc_etd
AS
SELECT
  `orc`.`orcchave` AS `orcchave`,
  `orc`.`flacodigo` AS `flacodigo`,
  IF(((`orc`.`etdcodigo` = 0) AND (`orc`.`orcnome` <> '')), CONCAT(`orc`.`orcnome`, IFNULL(CONCAT(' - ', `orc`.`orcendereco`), ''), IFNULL(CONCAT(' - ', `orc`.`orctelefone`), '')), `etd`.`etdidentificacao`) AS `etdidentificacao`
FROM (`orc`
  JOIN `etd`
    ON ((`orc`.`etdcodigo` = `etd`.`etdcodigo`)));

DROP TABLE IF EXISTS v_orc_totais;

CREATE OR REPLACE
DEFINER = 'root'@'localhost'
VIEW v_orc_totais
AS
SELECT
  `orc`.`orcchave` AS `orcchave`,
  `orc`.`flacodigo` AS `flacodigo`,
  IF((`orc`.`puocodigo` = 0), `orc`.`orcgeralav`, `orc`.`orcgeralap`) AS `orcgeral`,
  IF((`orc`.`puocodigo` = 0), `orc`.`orcdescontoav`, `orc`.`orcdescontoap`) AS `orcdesconto`,
  IF((`orc`.`puocodigo` = 0), `orc`.`orctotalav`, `orc`.`orctotalap`) AS `orctotal`
FROM `orc`;

DROP TABLE IF EXISTS v_rfibol;

CREATE OR REPLACE
DEFINER = 'root'@'localhost'
VIEW v_rfibol
AS
SELECT
  `rfi`.`rfichave` AS `rfichave`,
  `bol`.`bolchave` AS `bolchave`,
  `bol`.`bolnossonumero` AS `bolnossonumero`
FROM (`rfi`
  JOIN `bol`
    ON ((`rfi`.`rfichave` = `bol`.`rfichave`)))
WHERE (`rfi`.`tfdcodigo` = 2);

DROP TABLE IF EXISTS v_rfirfm;

CREATE OR REPLACE
DEFINER = 'root'@'localhost'
VIEW v_rfirfm
AS
SELECT
  `r`.`rfichave` AS `rfichave`,
  `r1`.`meschave` AS `meschave`,
  `r1`.`flacodigo` AS `flacodigo`
FROM (`rfi` `r`
  LEFT JOIN `rfm` `r1`
    ON (((`r`.`rfichave` = `r1`.`rfichave`)
    AND (`r`.`flacodigo` = `r1`.`flacodigo`))))
WHERE ((`r1`.`meschave` IS NOT NULL)
AND (`r`.`tfdcodigo` IN (1, 2)));

DROP TABLE IF EXISTS v_rfirng;

CREATE OR REPLACE
DEFINER = 'root'@'localhost'
VIEW v_rfirng
AS
SELECT
  `m`.`rfichave` AS `rfichave`,
  `r`.`rngchave` AS `rngchave`
FROM (((`mfi` `m`
  LEFT JOIN `mlt` `m1`
    ON ((`m`.`mfichave` = `m1`.`mfichave`)))
  LEFT JOIN `lte` `l`
    ON (((`m1`.`ltechave` = `l`.`ltechave`)
    AND (`l`.`tfdcodigo` = 62)
    AND (`l`.`ltesituacao` = 0))))
  LEFT JOIN `rng` `r`
    ON ((`l`.`ltechave` = `r`.`ltechave`)))
WHERE (`r`.`rngchave` IS NOT NULL)
GROUP BY `m`.`rfichave`;

DROP TABLE IF EXISTS v_vei_eqp;

CREATE OR REPLACE
DEFINER = 'root'@'localhost'
VIEW v_vei_eqp
AS
SELECT
  `orc`.`orcchave` AS `orcchave`,
  `vei`.`veicodigo` AS `veicodigo`,
  NULL AS `eqpcodigo`,
  IF((IFNULL(`vei`.`veiplaca`, '') <> ''), `vei`.`veiplaca`, `vei`.`veiniv`) AS `objidentificacao`,
  `vei`.`veimodelo` AS `objmodelo`
FROM ((`orc`
  JOIN `vor`
    ON ((`orc`.`orcchave` = `vor`.`orcchave`)))
  JOIN `vei`
    ON ((`vor`.`veicodigo` = `vei`.`veicodigo`)))
UNION
SELECT
  `orc`.`orcchave` AS `orcchave`,
  NULL AS `veicodigo`,
  `eqp`.`eqpcodigo` AS `eqpcodigo`,
  `eqp`.`eqpnumserie` AS `eqpnumserie`,
  `eqp`.`eqpidentificacao` AS `eqpidentificacao`
FROM (`orc`
  JOIN `eqp`
    ON ((`orc`.`eqpcodigo` = `eqp`.`eqpcodigo`)));

DROP TABLE IF EXISTS v_vrp;

CREATE OR REPLACE
DEFINER = 'root'@'localhost'
VIEW v_vrp
AS
SELECT
  `pro`.`procodigo` AS `procodigo`,
  `via`.`vrpcodigo` AS `vrpcodigo`,
  TRIM(CONCAT(`pro`.`pronome`, ' ', IFNULL(CAST(GROUP_CONCAT(`iat`.`iatidentificacao` ORDER BY `via`.`viacodigo` ASC SEPARATOR ' ') AS char(40) charset latin1), ''))) AS `pronome`,
  `vrp`.`vrpreferencia` AS `vrpreferencia`,
  `vrp`.`vrpbarra` AS `vrpbarra`,
  `vrp`.`vrpbarrasistema` AS `vrpbarrasistema`,
  `vrp`.`vrpsaldo` AS `vrpsaldo`
FROM (((`pro`
  JOIN `vrp`
    ON ((`pro`.`procodigo` = `vrp`.`procodigo`)))
  JOIN `via`
    ON ((`vrp`.`vrpcodigo` = `via`.`vrpcodigo`)))
  JOIN `iat`
    ON ((`via`.`iatcodigo` = `iat`.`iatcodigo`)))
GROUP BY `pro`.`procodigo`,
         `via`.`vrpcodigo`;

DROP TABLE IF EXISTS v_rcr;

CREATE OR REPLACE
DEFINER = 'root'@'%'
VIEW v_rcr
AS
SELECT
  `rcr`.`rcrchave` AS `rcrchave`,
  `tcr`.`tcridentificacao` AS `tcridentificacao`,
  `tsc`.`tscidentificacao` AS `tscidentificacao`,
  `etd`.`etdidentificacao` AS `etdidentificacao`,
  `rcr`.`etdcodigo` AS `etdcodigo`,
  `rcr`.`cedcodigo` AS `cedcodigo`,
  `rcr`.`rcrdata` AS `rcrdata`,
  `rcr`.`rcrhistorico` AS `rcrhistorico`,
  `mce`.`mcechave` AS `mcechave`,
  `tmc`.`tmcidentificacao` AS `tmcidentificacao`,
  `mce`.`tmccodigo` AS `tmccodigo`,
  `mce`.`ltechave` AS `ltechave`,
  `clb`.`clbcodigo` AS `clbcodigo`,
  `clb`.`clbidentificacao` AS `clbidentificacao`,
  `rcr`.`rcrvalor` AS `rcrvalor`,
  IF((`rcr`.`tsccodigo` = 1), COALESCE(`v_mcr`.`mcrvalor`, 0), `rcr`.`rcrvalor`) AS `mcrvalorbaixa`,
  IF((`rcr`.`tsccodigo` = 1), (`rcr`.`rcrvalor` - COALESCE(`v_mcr`.`mcrvalor`, 0)), 0) AS `rcrsaldo`,
  `mce`.`mcemotivo` AS `mcemotivo`,
  `mce`.`mecregistro` AS `mecregistro`,
  `rcr`.`tcrcodigo` AS `tcrcodigo`,
  `rcr`.`tsccodigo` AS `tsccodigo`,
  `rcr`.`tnccodigo` AS `tnccodigo`,
  `rcr`.`rcrhora` AS `rcrhora`
FROM ((((((((`rcr`
  LEFT JOIN `v_mcr`
    ON ((`v_mcr`.`rcrchave` = `rcr`.`rcrchave`)))
  JOIN `tcr`
    ON ((`rcr`.`tcrcodigo` = `tcr`.`tcrcodigo`)))
  JOIN `tsc`
    ON ((`rcr`.`tsccodigo` = `tsc`.`tsccodigo`)))
  JOIN `etd`
    ON ((`rcr`.`etdcodigo` = `etd`.`etdcodigo`)))
  JOIN `v_mce`
    ON ((`v_mce`.`rcrchave` = `rcr`.`rcrchave`)))
  JOIN `mce`
    ON ((`v_mce`.`mcechave` = `mce`.`mcechave`)))
  JOIN `tmc`
    ON ((`mce`.`tmccodigo` = `tmc`.`tmccodigo`)))
  JOIN `clb`
    ON ((`mce`.`clbcodigo` = `clb`.`clbcodigo`)));