--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.358.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10/12/2017 17:20:37
-- Server version: 5.7.20-log
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO umo(umocodigo, umoidentificacao, umosigla) VALUES
(1, 'REAL', 'R$')
ON DUPLICATE KEY UPDATE umocodigo=VALUES(umocodigo), umoidentificacao=VALUES(umoidentificacao), umosigla=VALUES(umosigla);
INSERT INTO umo(umocodigo, umoidentificacao, umosigla) VALUES
(2, 'SALÁRIO MÍNIMO', 'SM')
ON DUPLICATE KEY UPDATE umocodigo=VALUES(umocodigo), umoidentificacao=VALUES(umoidentificacao), umosigla=VALUES(umosigla);