unit MizioUP.Services.estilo;

interface

uses
  System.UITypes;

const
  PRIMARY = $FF8bc53d;
  SECONDARY = $FF6c757d;
  SUCCESS = $FF28a745;
  DANGER = $FFc8151c;
  WARNING = $FFfec83e;
  INFO = $FF658c33;
  LIGHT = $FFa2d164;
  LIGHT2 = $FFefefef;
  DARK = $FF343a40;
  BLACK = $FF000000;
  MUTED = $FFf9f8f8;
  WHITE = $FFffffff;

  FONT_SIZE_H1 = 30;
  FONT_SIZE_H2 = 28;
  FONT_SIZE_H3 = 26;
  FONT_SIZE_H4 = 24;
  FONT_SIZE_H5 = 22;
  FONT_SIZE_H6 = 20;
  FONT_SIZE_H7 = 18;
  FONT_SIZE_H8 = 16;
  FONT_SIZE_P  = 14;
  FONT_SIZE_XL = 55;

  //Mode Ligth
//  BACKGROUND = WHITE;
//  FONTCOLOR_H = BLACK;
//  FONTCOLOR_H2 = BLACK;
//  COLORDESTAK = DANGER;
//  FONTOCOLORDESTAK_H = WHITE;
//  BACKGROUND_ITEM = MUTED;
//  FONTCOLORSELECT = MUTED;

  //Mode Dark
  BACKGROUND = DARK;
  FONTCOLOR_H = WHITE;
  FONTCOLOR_H2 = WHITE;
  BACKGROUND_ITEM = $FF24282D;
  COLORDESTAK = DANGER;
  FONTOCOLORDESTAK_H = WHITE;
  FONTCOLORSELECTED = MUTED;
  BACKGROUND_BOTAOINATIVO = $FF24282D;
  BACKGROUND_BOTAOATIVO = MUTED;


  //Mode RED
 // BACKGROUND = DANGER;
 // FONTCOLOR_H = WARNING;
 // FONTCOLOR_H2 = DANGER;
 // BACKGROUND_ITEM = $FF9F1118;
 // COLORDESTAK = WARNING;
 // FONTOCOLORDESTAK_H = BLACK;
//  FONTCOLORSELECT = MUTED;

implementation

end.
